"""init

Revision ID: 0da731fc4f02
Revises: 
Create Date: 2017-04-07 11:39:05.683847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da731fc4f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('role_default', sa.Boolean(), nullable=True),
    sa.Column('role_permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_role_default'), 'roles', ['role_default'], unique=False)
    op.create_table('vulnseverities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnseverities_name'), 'vulnseverities', ['name'], unique=True)
    op.create_table('vulntypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulntypes_name'), 'vulntypes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('user_pwd_hash', sa.String(length=256), nullable=True),
    sa.Column('user_dept', sa.String(length=300), nullable=True),
    sa.Column('user_loc', sa.String(length=100), nullable=True),
    sa.Column('user_aboutme', sa.Text(), nullable=True),
    sa.Column('user_membersince', sa.DateTime(), nullable=True),
    sa.Column('user_lastseen', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_table('vulninfoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vuln_id', sa.String(length=100), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('vulntype_id', sa.Integer(), nullable=True),
    sa.Column('vulntype_alias_id', sa.Integer(), nullable=True),
    sa.Column('vuln_descript', sa.Text(), nullable=True),
    sa.Column('vuln_exploit', sa.Text(), nullable=True),
    sa.Column('cve_id', sa.String(length=100), nullable=True),
    sa.Column('bugtraq_id', sa.String(length=100), nullable=True),
    sa.Column('cnnvd_id', sa.String(length=100), nullable=True),
    sa.Column('vuln_solution', sa.Text(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['severity'], ['vulnseverities.id'], ),
    sa.ForeignKeyConstraint(['vulntype_alias_id'], ['vulntypes.id'], ),
    sa.ForeignKeyConstraint(['vulntype_id'], ['vulntypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulninfoes_vuln_id'), 'vulninfoes', ['vuln_id'], unique=False)
    op.create_table('cncpes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=300), nullable=True),
    sa.Column('vendor', sa.String(length=300), nullable=True),
    sa.Column('product', sa.String(length=300), nullable=True),
    sa.Column('version', sa.String(length=200), nullable=True),
    sa.Column('update', sa.String(length=200), nullable=True),
    sa.Column('edition', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=200), nullable=True),
    sa.Column('cncpeoperator', sa.String(length=100), nullable=True),
    sa.Column('vulninfo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vulninfo_id'], ['vulninfoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_table('vulnrefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_source', sa.String(length=300), nullable=True),
    sa.Column('ref_name', sa.String(length=300), nullable=True),
    sa.Column('ref_url', sa.String(length=300), nullable=True),
    sa.Column('vulninfo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vulninfo_id'], ['vulninfoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnsoftwarelists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('vulninfo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vulninfo_id'], ['vulninfoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnsoftwarelists_product'), 'vulnsoftwarelists', ['product'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnsoftwarelists_product'), table_name='vulnsoftwarelists')
    op.drop_table('vulnsoftwarelists')
    op.drop_table('vulnrefs')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('cncpes')
    op.drop_index(op.f('ix_vulninfoes_vuln_id'), table_name='vulninfoes')
    op.drop_table('vulninfoes')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_vulntypes_name'), table_name='vulntypes')
    op.drop_table('vulntypes')
    op.drop_index(op.f('ix_vulnseverities_name'), table_name='vulnseverities')
    op.drop_table('vulnseverities')
    op.drop_index(op.f('ix_roles_role_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
